### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by Walter1996AR** [feecat/OpenSML#3]
Hi,
I want to use this library but I have some problems settings thing up.
I get the following error:
'SM3_Drive_ETC_DS402_CyclicSync.AXIS_REF_ETC_DS402_CS' is not equal to type 'OpenSML_Axis' of VAR_IN_OUT 'Axis'
It would be of great help if somebody has a sample project for me, or can tell me what steps to take after importing this library.
Thanks in advance!!

**Comment by feecat** [comment]
Hi  
Please add a servo driver without *_SM and do not add softmotion or softmotionlight axis.  
Then you can define variable in program like this if you added library in codesys:
```
VAR
	Axis_X : OpenSML.OpenSML_Axis;
END_VAR
```
Or if you just add function block and struct, you can add variable like this:
```
VAR
	Axis_X : OpenSML_Axis;
END_VAR
```
  
Then just connect the variables to I/O mapping like this:

![Snipaste_2021-05-19_17-02-05](https://user-images.githubusercontent.com/29628990/118786187-26dc3a80-b8c4-11eb-8fe6-dbb8b3b23fef.png)

Then you can write yours code in POUs.  
Thanks.

**Comment by Walter1996AR** [comment]
Hi,

Thank you for your fast reply!! 
It looks like its working better now. But when I try to remap the IO I get the following error: map to existing variable with address is not allowed! 
Do you by any chance have an idea where this is coming from? 
Thanks again!

**Comment by feecat** [comment]
Hi
Could you share yours project files? I have nerver been seen this error.
Thanks.

**Comment by Walter1996AR** [comment]
Ofcourse, 
Please find attached the project archive.

**Comment by Walter1996AR** [comment]
Ofcourse, 
Please find it attached in the wetransfer link, the file was to big to upload directly. 
https://we.tl/t-3bBAtZbeYK
Kind regards and thanks again!

**Comment by feecat** [comment]
Hi
It seems that elconfa's library have some problem in struct define. You can edit library file, remove all of "AT %I*" and "AT %Q*" , Then save and import it.
![Snipaste_2021-05-20_17-32-03](https://user-images.githubusercontent.com/29628990/118955490-51e09000-b991-11eb-87b3-f95c95fb6489.png)
Thanks.

**Comment by Walter1996AR** [comment]
You are the man! Thank you. Seems like it is working now. 
Do you have by any chance a example project where the library is used? Nevertheless I want to thank you very much.

**Comment by feecat** [comment]
Hi
For now, I have only used this library on servotronix cdhd and leadshine dm3e. If you agree, you can share the project files after testing( delete others logic). I can pack them and put it on this repository homepage.  
Also im happy to answer if you have any questions.  
thanks
