### ISSUE TITLE
About QuickStop and Jog

### ISSUE THREAD

**Issue by ulysses936** [feecat/OpenSML#5]
I have a question about quickstop,in FunctionBlock OpenSML_Power I see the following code

`Axis.ControlWord.2:=xEmergencyStop;//QuickStop`
This means that the flag bit is set to 1 when I want to execute QuickStop cmd.

But in some documents about CiA402 ，it seems that in Normal state(e.g. Operation Enable) this bit2 flag is 1.
And, instead, this flag bit is set to 0 when the QuickStop command is executed.
Is this due to different drive manufacturers?

In addition, I think it is possible to achieve the Jog function by speed mode(Operation mode = 3).

**Comment by feecat** [comment]
hi
  xEmergencyStop direct connect to e-stop button, so it was 1 when normally.
  profile velocity mode have a problem that we cannot stop it immediately at software limit. Also standard softmotion lib have same problem.. normally we use mc_moveabsolute as jog cuz it was easy to apply software limit without any alarm.

thanks.

**Comment by ulysses936** [comment]
I understand, thank you very much for your answer
