### ISSUE TITLE
Connect real Motor with example provided.

### ISSUE THREAD

**Issue by nonpostrans** [feecat/OpenSML#7]
Hi!

Very nice project, but I am failing on adding my canOpen402 motor to the example.
The example uses an Axis Controller and and a Control unit - but which Axis I should use to map my motor to?

	AxisController : OpenSML_AxisController;
	con : OpenSML_Control;

I mapped the motor to con and If i turn the motor manually the actual position in the VISU changes - so that works.
But the rest doesnt work. 

con.xSimulation:=FALSE;

I changed this to false as I am using a real motor.

Check my screenshot, I guess my mapping is wrong?

Thanks a lot!!

![SML](https://github.com/user-attachments/assets/9d6b7914-035e-47ad-ab69-797158a39072)

**Comment by feecat** [comment]
Hi,
Mapping seems fine. I had noticed that controlword = 4, it means axis not enable. Try click "enable" button on visulization or set con.xAxisEnable?

**Comment by nonpostrans** [comment]
Hi!
My current program looks like that:

```
AxisController(Axis:=con.axis , Control:=con);
con.xSimulation:=FALSE;
con.xAxisEnable := TRUE;
con.xEnabled := TRUE;
```

I realized that when I set `con.xMoveEnable` via the GUI `con.xError `till turn to TRUE, so an error state.
I checked the state machine of AxisController and I think in is this line:

`ELSIF Control.xMoveEnable AND Axis.StatusWord.1 AND Axis.Modes_of_operation_display <> 8 THEN//need switch mode`

Condition is never met because `Axis.StatusWord.1 ` is not true. Bit one is "Switched On" but where is the state machine put into that state? Maybe I am also wrong. 

Controlword changed to 6.

Thanks for your support!

![sml3](https://github.com/user-attachments/assets/97700025-f0c5-4be2-83e2-48e5fa8033cb)
![sml1](https://github.com/user-attachments/assets/9c72601d-7a91-495d-a69b-c629c643e90e)

**Comment by feecat** [comment]
Hi,

xAxisEnable should set before xMoveEnable, ControlWord control by OpenSML_Power.  
In you screenshoot i can see controlword = 6, means control.2 and control.1 is TRUE. You can check OpenSML_Power, it should into step 20 but why not go 30? Could you upload your project file?

![image](https://github.com/user-attachments/assets/8b6b7f2e-8236-401c-ab4e-fca40c40da1b)

BTW, if you use opensml, please remove axis in device tree. otherwise process data could be overwrite.

**Comment by nonpostrans** [comment]
Hello!
Now it is working, thank you.
However, I want to use ProfilePosition mode and I dont understand how to put the motor in operation properly.
I connected` con.xAxisEnable` and` con.xMoveEnable`and  `MC_Linear.xEnable` to GUI switches for testing.
If I manually turn on xAxisEnable, then xMoveEnable and after that enable ProfilePosition FB with xEnable it works. I can execute movement on the real motor.

Now I want to use a state machine to do this:

```
VAR
	AxisController : OpenSML_AxisController;
	MC_Linear : OpenSML_ProfilePosition;
        Home_X : OpenSML_Home;
	con : OpenSML_Control;
	iState : INT := 0;
END_VAR
```
```
AxisController(Axis:=con.axis , Control:=con);
con.xSimulation:=FALSE;

CASE iState OF
	
	0: con.xAxisEnable := TRUE; 
		IF con.xEnabled THEN. //<- Condition never true
			con.xMoveEnable := TRUE;
			MC_Linear.xEnable := TRUE;
			iState:=10;
		END_IF
	
	10:	
		//Home_X(Axis:=con.Axis);
		iState:=20;
END_CASE
```

`con.xEnabled`  will not switch to TRUE.
I dont know, maybe I need to wait until communication with the motor is established before setting `con.xAxisEnable := TRUE; `

Thanks for your support!

**Comment by feecat** [comment]
Hi, 
Currently most servo driver that use ethercat protocol is cia402 standard, it means driver work on CSP mode default.  
If you controller have enough real-time performance, you should use CSP mode.  

If you really want use PP( ProfilePosition), you need modify pdo data, enable profile position/ target velocity/ modes of operation. I had notice that your screenshot already config ok, thats good.  
You should config ACC/DEC, Speed curve, filter etc on servo driver when use PP mode.
AxisController is a demo with CSP. If you want use PP, you sould use that code:
```
CASE iState OF
	0:
		Power_X(Axis:=Axis_X,xEnable:=xStart);
		IF Power_X.xDone THEN
			iState:=10;
		END_IF;
	10:
		Home_X(Axis:=Axis_X , xEnable:=xHomeEnable);
		IF Home_X.xDone THEN
			iState:=20;
		END_IF
	20:
		ProfilePosition_X(
			Axis:=Axis_X , 
			xEnable:=xMoveEnable , 
			xExecute:=xMoveExecute , 
			xContinueMove:=FALSE , 
			xRelativeMode:=FALSE , 
			diTargetPosition:=diTarget , 
			udiProfileVelocity:=udiVel);
END_CASE
```

**Comment by nonpostrans** [comment]
Hi!

Due to several reasons I don't want to use CSP mode, although I know that this is the key functionality of this library.

However I found a bug in OpenSML_ProfilePosition

`IF xEnable AND Axis.StatusWord.1 AND Axis.StatusWord.2 AND Axis.Modes_of_operation_display = 3 AND NOT Axis.StatusWord.3 THEN//ready`

`Axis.Modes_of_operation_display = 3` is wrong because here we check for Profile Position Mode which is mode one.

`Axis.Modes_of_operation_display = 1` is correct.

I am not a programmer so please double check!

Thanks for your amazing work!

**Comment by feecat** [comment]
Hi,

You are right, i will fix it. Thanks you.

If you have others problem please feel free to ask.

**Comment by seipv** [comment]
Hi Feecat!
Is possible to use this OpenSML to older Codesys 2.3?
Excellent work!

**Comment by feecat** [comment]
> Hi Feecat! Is possible to use this OpenSML to older Codesys 2.3? Excellent work!

Hi,

I don't think it's possible cuz 2.x doesn't support Object-Oriented Programming (OOP), while Ruckig makes use of OOP. However, if you have the patience, it could be ported.

If you considering of cost, you can using Twincat2 ( I hear some manufacturers offer a keygen).

**Comment by feecat** [comment]
> Hi Feecat!
> 
> Think have the same issue with Power FB is which to error no matter how i time commutate true signal. Any ide what i'm doing wrong?
> 

Seems like you are not connect to real cia402 servodrive.  
its suggest that use standard softmotion fb to test connection.

**Comment by seipv** [comment]
![Image](https://github.com/user-attachments/assets/a9cf9a81-80c0-4c92-b594-7ba5592adc9a) 
Eventually i got it to work in simulation mode as long xAxisEnable is OFF iStatr:20 and with xFollowEnable can switch between Velocity and Postion. Enclear why Power is always xError.

**Comment by seipv** [comment]
Want to implement this OpenSML to a hydraulic drive for position control and test the achieved accuracy. Setup is simple, CR2040 I/O control the solenoids and take drive absolute position sensor via CAN and send it thought CAN to CR1140 where OpenSML do its business. So far main issue i see that I'm not able to set OpenSML in work by activating logical input with FB. I cannot use any SoftMotion block that are in Codesys since they are under license... In Simulation mode got actual position movement but seem wrong way to try to adopt that way and feed actual sensor and hope for the best, what can be done to go around the physical missing of CIA402 servo drive and use OpenSML to move classics hydraulic position drives ?

**Comment by feecat** [comment]
@seipv Hi, 
You should use servo drives that support CiA402, such as servo-hydraulics. These drives support encoder feedback and can be used in the same way as ordinary servo drives. Both opensml and softmotion are motion control solutions; they do not read feedback values (from encoders), but instead calculate target positions and send them to the drive for execution. If the drive does not support CiA402, you need to achieve control through other methods such as PID or FUZZY, which is usually more complex than switching to a servo system.

If you are already using servo-hydraulics, you can eliminate the error between the built-in encoder and the external encoder by using a method similar to superposition. For example, during motion, check the error between the built-in encoder and the external encoder every 100ms, and superimpose this error onto the target position.

Finally, if you have any other questions, please feel free to raise a new issue. Asking questions here will cause other people to receive spam emails that do not pertain to their topics.
